import { useState, useEffect, useRef, useCallback } from "react";
const S2T_MAP = {"爱":"愛","罢":"罷","备":"備","贝":"貝","笔":"筆","毕":"畢","边":"邊","变":"變","标":"標","别":"別","补":"補","参":"參","产":"產","长":"長","场":"場","车":"車","称":"稱","齿":"齒","冲":"衝","虫":"蟲","处":"處","传":"傳","窗":"窗","从":"從","错":"錯","达":"達","带":"帶","单":"單","导":"導","灯":"燈","点":"點","电":"電","东":"東","动":"動","断":"斷","队":"隊","对":"對","发":"發","飞":"飛","费":"費","风":"風","复":"復","盖":"蓋","干":"乾","刚":"剛","个":"個","给":"給","跟":"跟","够":"夠","关":"關","观":"觀","广":"廣","过":"過","还":"還","汉":"漢","号":"號","河":"河","后":"後","护":"護","话":"話","画":"畫","怀":"懷","换":"換","黄":"黃","会":"會","机":"機","极":"極","几":"幾","际":"際","继":"繼","价":"價","见":"見","将":"將","奖":"獎","节":"節","尽":"盡","经":"經","举":"舉","开":"開","块":"塊","来":"來","劳":"勞","乐":"樂","类":"類","离":"離","历":"歷","联":"聯","两":"兩","临":"臨","灵":"靈","龙":"龍","楼":"樓","路":"路","乱":"亂","妈":"媽","买":"買","满":"滿","门":"門","面":"麵","庙":"廟","灭":"滅","难":"難","内":"內","脑":"腦","你":"你","鸟":"鳥","农":"農","强":"強","亲":"親","情":"情","区":"區","热":"熱","认":"認","时":"時","实":"實","书":"書","树":"樹","说":"說","岁":"歲","台":"臺","态":"態","体":"體","听":"聽","头":"頭","团":"團","万":"萬","为":"為","问":"問","无":"無","务":"務","习":"習","现":"現","线":"線","乡":"鄉","响":"響","向":"向","协":"協","写":"寫","寻":"尋","学":"學","选":"選","压":"壓","严":"嚴","样":"樣","业":"業","义":"義","应":"應","营":"營","拥":"擁","优":"優","鱼":"魚","语":"語","园":"園","远":"遠","运":"運","战":"戰","这":"這","真":"真","证":"證","只":"只","种":"種","众":"眾","转":"轉","装":"裝","状":"狀","资":"資","总":"總","组":"組"};
function simplifiedToTraditional(t){return t.split("").map(c=>S2T_MAP[c]||c).join("")}
function detectChapters(content){const lines=content.split("\n");const chapters=[];const re=/^(第[零一二三四五六七八九十百千\d]+[章節回卷部]|Chapter\s*\d+|CHAPTER\s*\d+|卷[零一二三四五六七八九十百千\d]+)/;lines.forEach((line,idx)=>{const t=line.trim();if(t&&re.test(t))chapters.push({title:t,lineIndex:idx})});if(chapters.length===0||chapters[0].lineIndex>0)chapters.unshift({title:"開頭",lineIndex:0});return chapters}
function parseEpub(ab){const t=new TextDecoder("utf-8").decode(ab);return t.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function parseTxt(ab){return new TextDecoder("utf-8").decode(ab)}
const SAMPLE=`第一章\n\n小時候，有一次我在一本描寫原始森林的書裡，看到了一幅精彩的插圖。那本書叫做《真實的故事》。那幅圖畫的是一條蟒蛇，正在吞食一頭猛獸。\n\n在書上說，蟒蛇把獵獲的動物不加咀嚼，整個地吞下去，然後就再也不能動彈了，就這樣沉睡六個月，等著消化吃進去的食物。\n\n第二章\n\n這樣，我只好選擇了另一個職業，學會了開飛機。世界各地差不多我都飛到過。不錯，地理學確實幫了我很大的忙。\n\n第三章\n\n就這樣，我孤獨地生活著，沒有一個真正可以交心的人，直到六年前，在撒哈拉沙漠發生了飛機故障。`;
const BOOKS0=[{id:"s1",title:"小王子",author:"聖-埃克蘇佩里",content:SAMPLE,progress:0,bookmarks:[],converted:false}];
const FSZ=[14,16,18,20,22,24,28];
const CC=[["#c4704a","#8b4a2e"],["#4a7c8b","#2e5a6b"],["#6b8b4a","#4a6b2e"],["#8b4a7c","#6b2e5a"]];
export default function App(){
const [books,setBooks]=useState(BOOKS0);
const [cur,setCur]=useState(null);
const [view,setView]=useState("library");
const [dark,setDark]=useState(false);
const [fs,setFs]=useState(18);
const [bright,setBright]=useState(1);
const [sets,setSets]=useState(false);
const [bms,setBms]=useState(false);
const [chaps,setChaps]=useState(false);
const [prog,setProg]=useState(0);
const [tts,setTts]=useState(false);
const [rate,setRate]=useState(1);
const [bfb,setBfb]=useState(null);
const rdr=useRef(null);
const fir=useRef(null);
const utt=useRef(null);
const tfr=useRef({active:false,startY:0,startB:1});
const fbt=useRef(null);
const chapters=cur?detectChapters(cur.content):[];
function showBF(v){setBfb(Math.round(v*100));clearTimeout(fbt.current);fbt.current=setTimeout(()=>setBfb(null),1200)}
function onTS(e){if(e.touches.length===2){const y=(e.touches[0].clientY+e.touches[1].clientY)/2;tfr.current={active:true,startY:y,startB:bright};e.preventDefault()}}
function onTM(e){if(!tfr.current.active||e.touches.length!==2)return;const y=(e.touches[0].clientY+e.touches[1].clientY)/2;const d=(tfr.current.startY-y)/300;const nb=Math.min(1,Math.max(0.2,tfr.current.startB+d));setBright(nb);showBF(nb);e.preventDefault()}
function onTE(e){if(e.touches.length<2)tfr.current.active=false}
const onScroll=useCallback(()=>{if(!rdr.current)return;const el=rdr.current;const p=el.scrollTop/(el.scrollHeight-el.clientHeight);const pv=Math.min(1,Math.max(0,p));setProg(pv);if(cur)setBooks(prev=>prev.map(b=>b.id===cur.id?{...b,progress:pv}:b))},[cur]);
useEffect(()=>{const el=rdr.current;if(el){el.addEventListener("scroll",onScroll);return()=>el.removeEventListener("scroll",onScroll)}},[onScroll,view]);
useEffect(()=>{if(view==="reader"&&cur&&rdr.current){const el=rdr.current;setTimeout(()=>{el.scrollTop=cur.progress*(el.scrollHeight-el.clientHeight)},60)}},[view]);
function stopTTS(){window.speechSynthesis?.cancel();setTts(false)}
function startTTS(){if(!cur||!window.speechSynthesis)return;stopTTS();const u=new SpeechSynthesisUtterance(cur.content);u.lang="zh-TW";u.rate=rate;u.onend=()=>setTts(false);utt.current=u;window.speechSynthesis.speak(u);setTts(true)}
function toggleTTS(){tts?stopTTS():startTTS()}
useEffect(()=>{return()=>stopTTS()},[]);
useEffect(()=>{if(tts){stopTTS();startTTS()}},[rate]);
function openBook(b){setCur(b);setView("reader");setSets(false);setBms(false);setChaps(false);stopTTS()}
function addBM(){if(!cur)return;const bm={id:Date.now(),progress:prog,label:`第${Math.round(prog*100)}%處`};setBooks(p=>p.map(b=>b.id===cur.id?{...b,bookmarks:[...b.bookmarks,bm]}:b));setCur(p=>({...p,bookmarks:[...p.bookmarks,bm]}))}
function delBM(id){setBooks(p=>p.map(b=>b.id===cur.id?{...b,bookmarks:b.bookmarks.filter(x=>x.id!==id)}:b));setCur(p=>({...p,bookmarks:p.bookmarks.filter(x=>x.id!==id)}))}
function jumpBM(bm){if(!rdr.current)return;rdr.current.scrollTop=bm.progress*(rdr.current.scrollHeight-rdr.current.clientHeight);setBms(false)}
function jumpCh(ch){if(!rdr.current)return;const lines=cur.content.split("\n");const cb=lines.slice(0,ch.lineIndex).join("\n").length;const r=cb/cur.content.length;rdr.current.scrollTop=r*(rdr.current.scrollHeight-rdr.current.clientHeight);setChaps(false)}
function delBook(id){setBooks(p=>p.filter(b=>b.id!==id))}
function toggleConv(){if(!cur)return;const nc=!cur.converted;const ct=nc?simplifiedToTraditional(cur.content):cur.content;setBooks(p=>p.map(b=>b.id===cur.id?{...b,converted:nc,content:ct}:b));setCur(p=>({...p,converted:nc,content:ct}))}
async function upload(e){const f=e.target.files[0];if(!f)return;const ab=await f.arrayBuffer();const c=f.name.endsWith(".epub")?parseEpub(ab):parseTxt(ab);setBooks(p=>[...p,{id:Date.now().toString(),title:f.name.replace(/\.(txt|epub)$/i,""),author:"未知作者",content:c,progress:0,bookmarks:[],converted:false}]);e.target.value=""}
const bg=dark?"#1a1a1a":"#faf7f2";const sf=dark?"#242424":"#fff";const tc=dark?"#e8e0d0":"#2c2416";const mu=dark?"#888":"#9a8f7e";const ac="#c4704a";const bd=dark?"#333":"#e8e0d0";
const ib={background:"none",border:"none",cursor:"pointer",padding:"8px 12px",borderRadius:8,fontSize:14,color:tc,display:"flex",alignItems:"center",gap:6};
const pn={position:"fixed",top:0,right:0,bottom:0,width:280,background:sf,borderLeft:`1px solid ${bd}`,zIndex:100,display:"flex",flexDirection:"column",boxShadow:"-4px 0 20px rgba(0,0,0,0.1)"};
function Cover({i}){const[c1,c2]=CC[i%CC.length];return <div style={{height:160,display:"flex",alignItems:"center",justifyContent:"center",background:`linear-gradient(135deg,${c1},${c2})`}}><span style={{fontSize:48}}>📖</span></div>}
if(view==="library")return(<div style={{minHeight:"100vh",background:bg,color:tc,fontFamily:"Georgia,serif",filter:`brightness(${bright})`}}><input ref={fir} type="file" accept=".txt,.epub" style={{display:"none"}} onChange={upload}/><div style={{padding:"32px 24px 16px",borderBottom:`1px solid ${bd}`,display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{fontSize:26,fontWeight:"bold"}}>我的書庫</div><div style={{display:"flex",gap:12}}><button style={ib} onClick={()=>setDark(d=>!d)}>{dark?"☀️":"🌙"}</button><button style={{background:ac,color:"#fff",border:"none",borderRadius:10,padding:"10px 18px",cursor:"pointer",fontSize:14,fontWeight:"bold"}} onClick={()=>fir.current?.click()}>＋ 匯入書籍</button></div></div>{books.length===0?<div style={{textAlign:"center",padding:"80px 24px",color:mu}}><div style={{fontSize:48,marginBottom:16}}>📚</div><div style={{fontSize:18,color:tc,marginBottom:8}}>書庫是空的</div><div style={{fontSize:14}}>點擊匯入書籍上傳TXT或EPUB</div></div>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(160px,1fr))",gap:20,padding:24}}>{books.map((b,i)=><div key={b.id} style={{background:sf,borderRadius:14,overflow:"hidden",cursor:"pointer",border:`1px solid ${bd}`,position:"relative"}} onClick={()=>openBook(b)} onMouseEnter={e=>{e.currentTarget.style.transform="translateY(-4px)";e.currentTarget.querySelector(".db").style.opacity="1"}} onMouseLeave={e=>{e.currentTarget.style.transform="";e.currentTarget.querySelector(".db").style.opacity="0"}}><Cover i={i}/><button className="db" style={{position:"absolute",top:8,right:8,background:"rgba(0,0,0,0.5)",color:"#fff",border:"none",borderRadius:"50%",width:24,height:24,cursor:"pointer",opacity:0}} onClick={e=>{e.stopPropagation();delBook(b.id)}}>✕</button><div style={{height:3,background:dark?"#333":"#ede9e2"}}><div style={{height:"100%",background:ac,width:`${(b.progress||0)*100}%`}}/></div><div style={{padding:"12px 14px"}}><div style={{fontSize:14,fontWeight:"bold",color:tc,marginBottom:4}}>{b.title}</div><div style={{fontSize:12,color:mu}}>{b.author}</div>{b.progress>0&&<div style={{fontSize:11,color:ac,marginTop:4}}>已讀{Math.round(b.progress*100)}%</div>}</div></div>)}</div>}</div>);
const anyP=sets||bms||chaps;
return(<div style={{background:bg,color:tc,fontFamily:"Georgia,serif",display:"flex",flexDirection:"column",height:"100vh",overflow:"hidden",filter:`brightness(${bright})`}} onTouchStart={onTS} onTouchMove={onTM} onTouchEnd={onTE}>
{bfb!==null&&<div style={{position:"fixed",top:"50%",left:"50%",transform:"translate(-50%,-50%)",background:"rgba(0,0,0,0.7)",color:"#fff",borderRadius:16,padding:"16px 28px",fontSize:24,fontWeight:"bold",zIndex:200,pointerEvents:"none"}}>☀️{bfb}%</div>}
<div style={{padding:"14px 20px",borderBottom:`1px solid ${bd}`,display:"flex",alignItems:"center",justifyContent:"space-between",background:sf,flexShrink:0}}><button style={ib} onClick={()=>{setView("library");setSets(false);setBms(false);setChaps(false);stopTTS()}}>← 書庫</button><div style={{flex:1,textAlign:"center",fontSize:15,fontWeight:"bold",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",padding:"0 8px"}}>{cur?.title}</div><div style={{display:"flex",gap:2}}><button style={ib} onClick={addBM}>🔖</button><button style={{...ib,color:tts?ac:tc}} onClick={toggleTTS}>🔊</button><button style={ib} onClick={()=>{setChaps(s=>!s);setSets(false);setBms(false)}}>📋</button><button style={ib} onClick={()=>{setBms(s=>!s);setSets(false);setChaps(false)}}>📑</button><button style={ib} onClick={()=>{setSets(s=>!s);setBms(false);setChaps(false)}}>⚙️</button></div></div>
{tts&&<div style={{background:dark?"#2a2a2a":"#fff8f3",borderBottom:`1px solid ${bd}`,padding:"8px 20px",display:"flex",alignItems:"center",gap:12,flexShrink:0}}><span style={{fontSize:13,color:ac,fontWeight:"bold"}}>🔊語音朗讀中</span>{[0.75,1,1.25,1.5,2].map(r=><button key={r} style={{background:rate===r?ac:dark?"#333":"#eee",color:rate===r?"#fff":tc,border:"none",borderRadius:6,padding:"4px 10px",cursor:"pointer",fontSize:12}} onClick={()=>setRate(r)}>{r}x</button>)}<button style={{marginLeft:"auto",background:"none",border:`1px solid ${bd}`,borderRadius:6,padding:"4px 10px",cursor:"pointer",fontSize:12,color:tc}} onClick={stopTTS}>停止</button></div>}
<div style={{height:2,background:dark?"#333":"#ede9e2",flexShrink:0}}><div style={{height:"100%",background:ac,width:`${prog*100}%`}}/></div>
<div ref={rdr} style={{flex:1,overflowY:"auto",padding:"32px 24px",maxWidth:680,margin:"0 auto",width:"100%",lineHeight:1.9,fontSize:fs,color:tc,whiteSpace:"pre-wrap",wordBreak:"break-word"}}>{cur?.content}<div style={{height:80}}/></div>
<div style={{padding:"8px 24px",fontSize:12,color:mu,borderTop:`1px solid ${bd}`,background:sf,display:"flex",justifyContent:"space-between",flexShrink:0}}><span>兩指上下滑動調整亮度</span><span>進度{Math.round(prog*100)}%</span></div>
{anyP&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.3)",zIndex:99}} onClick={()=>{setSets(false);setBms(false);setChaps(false)}}/>}
{sets&&<div style={pn}><div style={{padding:"20px",borderBottom:`1px solid ${bd}`,display:"flex",justifyContent:"space-between",fontWeight:"bold",fontSize:16}}><span>設定</span><button style={{...ib,padding:4}} onClick={()=>setSets(false)}>✕</button></div><div style={{flex:1,overflowY:"auto",padding:16}}><div style={{marginBottom:24}}><div style={{fontSize:13,color:mu,marginBottom:10}}>字體大小</div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{FSZ.map(s=><button key={s} style={{padding:"8px 12px",borderRadius:8,border:`1px solid ${fs===s?ac:bd}`,cursor:"pointer",fontSize:13,background:fs===s?ac:dark?"#2e2e2e":"#f5f0ea",color:fs===s?"#fff":tc}} onClick={()=>setFs(s)}>{s}</button>)}</div></div><div style={{marginBottom:24}}><div style={{fontSize:13,color:mu,marginBottom:10}}>主題</div><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"12px 16px",background:dark?"#2e2e2e":"#f5f0ea",borderRadius:10,cursor:"pointer"}} onClick={()=>setDark(d=>!d)}><span>{dark?"🌙夜間":"☀️白天"}</span><span style={{width:40,height:22,background:dark?ac:"#ccc",borderRadius:11,position:"relative",display:"inline-block"}}><span style={{position:"absolute",top:2,left:dark?20:2,width:18,height:18,background:"#fff",borderRadius:"50%",transition:"left 0.3s"}}/></span></div></div><div style={{marginBottom:24}}><div style={{fontSize:13,color:mu,marginBottom:10}}>亮度{Math.round(bright*100)}%</div><input type="range" min={20} max={100} value={Math.round(bright*100)} onChange={e=>{const v=e.target.value/100;setBright(v);showBF(v)}} style={{width:"100%",accentColor:ac}}/></div><div style={{marginBottom:24}}><div style={{fontSize:13,color:mu,marginBottom:10}}>文字轉換</div><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"12px 16px",background:dark?"#2e2e2e":"#f5f0ea",borderRadius:10,cursor:"pointer"}} onClick={toggleConv}><span>🔄簡體→繁體</span><span style={{width:40,height:22,background:cur?.converted?ac:"#ccc",borderRadius:11,position:"relative",display:"inline-block"}}><span style={{position:"absolute",top:2,left:cur?.converted?20:2,width:18,height:18,background:"#fff",borderRadius:"50%",transition:"left 0.3s"}}/></span></div></div></div></div>}
{chaps&&<div style={pn}><div style={{padding:"20px",borderBottom:`1px solid ${bd}`,display:"flex",justifyContent:"space-between",fontWeight:"bold",fontSize:16}}><span>章節({chapters.length})</span><button style={{...ib,padding:4}} onClick={()=>setChaps(false)}>✕</button></div><div style={{flex:1,overflowY:"auto",padding:16}}>{chapters.map((ch,i)=><div key={i} style={{padding:"12px 14px",borderRadius:10,marginBottom:8,background:dark?"#2e2e2e":"#f5f0ea",cursor:"pointer"}} onClick={()=>jumpCh(ch)}><div style={{fontSize:14,fontWeight:"bold",color:tc}}>{ch.title}</div><div style={{fontSize:11,color:mu,marginTop:2}}>第{i+1}章</div></div>)}</div></div>}
{bms&&<div style={pn}><div style={{padding:"20px",borderBottom:`1px solid ${bd}`,display:"flex",justifyContent:"space-between",fontWeight:"bold",fontSize:16}}><span>書籤({cur?.bookmarks?.length||0})</span><button style={{...ib,padding:4}} onClick={()=>setBms(false)}>✕</button></div><div style={{flex:1,overflowY:"auto",padding:16}}>{!cur?.bookmarks?.length?<div style={{color:mu,textAlign:"center",padding:"32px 0"}}><div style={{fontSize:32,marginBottom:8}}>🔖</div>尚無書籤</div>:cur.bookmarks.map(bm=><div key={bm.id} style={{padding:"12px 14px",borderRadius:10,marginBottom:8,background:dark?"#2e2e2e":"#f5f0ea",display:"flex",alignItems:"center",cursor:"pointer"}}><div style={{flex:1}} onClick={()=>jumpBM(bm)}><div style={{fontSize:14,fontWeight:"bold"}}>{bm.label}</div><div style={{fontSize:12,color:mu}}>{Math.round(bm.progress*100)}%處</div></div><button style={{background:"none",border:"none",color:mu,cursor:"pointer",fontSize:16}} onClick={()=>delBM(bm.id)}>✕</button></div>)}</div></div>}
</div>);}

